<?php

/**
 * ActivitySurveyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivitySurveyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivitySurveyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivitySurvey');
    }
}