<?php

/**
 * AssociationSurveyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssociationSurveyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssociationSurveyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssociationSurveyCategory');
    }
}