<?php

/**
 * AssociationDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssociationDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssociationDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssociationDepartment');
    }
}