<?php

/**
 * AssociationSurveyDepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssociationSurveyDepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssociationSurveyDepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssociationSurveyDepartment');
    }
}