<?php

/**
 * Banner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner extends BaseBanner
{

	public function delete(Doctrine_Connection $conn = null) {
	
		$dir = '/var/chroot/home/content/32/7995832/html/guatevoluntaria/uploads';
		$fullpath = $dir . '/banners/'.$this->getPath();
		
		if( file_exists( $fullpath ) ) {
			unlink( $fullpath );	
		}
	
		return parent::delete($conn);
	}

}
