<?php

/**
 * InterestingLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InterestingLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InterestingLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InterestingLink');
    }
}