<?php

/**
 * LibraryRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibraryRatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibraryRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibraryRating');
    }
}