<?php

/**
 * LibraryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibraryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibraryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Library');
    }
}