<?php

/**
 * LibraryCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibraryCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibraryCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibraryComment');
    }
}