<?php

/**
 * TownTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TownTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TownTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Town');
    }
}