<?php

/**
 * VolunteerSurveyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VolunteerSurveyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VolunteerSurveyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VolunteerSurvey');
    }
}