<?php

/**
 * VolunteerSurveyAssociationSurveyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VolunteerSurveyAssociationSurveyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VolunteerSurveyAssociationSurveyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VolunteerSurveyAssociationSurvey');
    }
}