<?php

/**
 * VolunteerSurvey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VolunteerSurvey extends BaseVolunteerSurvey
{
	
	public function getActivities()
	{
		$result = Doctrine_Core::getTable('ActivitySurvey')
					->createQuery('a')
					->where( 'volunteer_survey_id = '.$this->getId() )
					->execute();
		return $result;
	}
	
	public static function getMaxNumberOfActivities()
	{
		$max = 0;
		$volunteers = Doctrine_Core::getTable('VolunteerSurvey')
					->createQuery('a')
					->execute();
		
		foreach( $volunteers as $volunteer )
		{
			$count = Doctrine_Core::getTable('ActivitySurvey')
					->createQuery('a')
					->where( 'volunteer_survey_id = '.$volunteer->getId() )
					->count();
			
			if( $count > $max )
				$max = $count;
		}
		
		return $max;
	}
	
}
