generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Activity
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [title, association, is_active, _show_photo, created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
