version: '3.3'

services:
    php:
        build: ./docker/php-fpm
        expose:
          - "9000"
          - "9001"
        ports:
          - "127.0.0.1:9016:9000"
          - "127.0.0.1:9017:9001"
        networks:
          - backend
        volumes:
          - ./Web:/var/www/symfony
          - ./logs/symfony:/var/www/symfony/var/logs
        restart: always
        env_file: ./mysql.env
    tools:
        build: ./docker/php-tools
        volumes:
            - ./Web:/var/www/symfony
        networks:
          - backend
        env_file: ./mysql.env
    nginx:
        build: ./docker/nginx
        ports:
            - "127.0.0.1:8484:80"
        networks:
          - backend
          - frontend
        depends_on:
          - php
        volumes:
          - ./Web/web:/var/www/symfony/web
          - ./docker/nginx/conf-main:/etc/nginx/conf.d
          - ./logs/nginx/:/var/log/nginx
        restart: always


networks:
  frontend:
  backend:

          #volumes:
        #  db-data:
