version: '3.3'

services:
    db:
        image: mysql
        networks:
          - backend
        expose:
          - "3306"
        volumes:
          - db-data:/var/lib/mysql
          - ./restore:/restore
        restart: always
        env_file: ./mysql.env
    php:
        build: ./docker/php-fpm
        expose:
          - "9001"
        networks:
          - backend
        volumes:
          - ./Web:/var/www/symfony
          - ./logs/symfony:/var/www/symfony/var/logs
        restart: always
        env_file: ./mysql.env
    tools:
        build: ./docker/php-tools
        volumes:
            - ./Web:/var/www/symfony
        networks:
          - backend
        env_file: ./mysql.env
    nginx:
        build: ./docker/nginx
        ports:
            - "8484:80"
        networks:
          - backend
          - frontend
        depends_on:
          - php
          - db
        volumes:
          - ./Web/web:/var/www/symfony/web
          - ./docker/nginx/conf-main:/etc/nginx/conf.d
          - ./logs/nginx/:/var/log/nginx
        restart: always
#    sass:
#        build: ./docker/sass
#        command: "sass /var/www/symfony/web/scss/custom.scss /var/www/symfony/web/output/custom.css --style compressed && sass /var/www/symfony/web/scss/login.scss /var/www/symfony/web/output/login.css --style compressed"
#        volumes:
#            - ./Web/web:/var/www/symfony/web


networks:
  frontend:
  backend:

volumes:
  db-data:
