generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Association
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          association
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [name, email, phone1, _show_photo, approved]
      filter:  ~
      form:
        class:		AssociationBackendForm
      edit:    ~
      new:     ~
