<?php

namespace World\DashboardBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends EntityRepository
{
}
