<?php

namespace World\AdminBundle\Entity\Repositories;

use World\ToolBundle\Entity\Repositories\BaseRepository;

/**
 * SlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideRepository extends BaseRepository
{

    public function findAllQuery( $enabled = null ) {

        $today = new \DateTime();

        $queryBuilder = $this->findAllQueryBuilder( $enabled )->orderBy('a.sortOrder', 'DESC');

        $queryBuilder->andWhere('a.startDate <= :today')
            ->andWhere('a.endDate >= :today')
            ->setParameter('today', $today->format('Y-m-d'))
        ;

        return $queryBuilder->getQuery();
    }

    public function findAllCustom( $enabled = null ) {
        return $this->findAllQuery( $enabled )->execute();
    }

}