# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

indexSuccess:
  metas:
    title:         Cultura del Voluntariado - GuateVoluntaria.org
    keywords:      voluntarios, voluntariado, trabajo voluntario, voluntarios en guatemala, voluntariado en guatemala, guatemala que hago por ti, que hago por ti, guatemala
    description:   Directorio de Voluntariado en Guatemala, contamos con listado de voluntariados y sus actividades futuras, necesitamos tu ayuda para construir una mejor Guatemala.

showSuccess:
  javascripts:    [jquery.min.js]
