<?php

namespace World\ToolBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository {

	public function addQueryParam( $query, $parameter, $name ) {
		if( $parameter != null ) {
			$query
				->andWhere( 'a.'.$name.' = :'.$name )
				->setParameter( $name, $parameter )
			;
		}
	}

	public function addJoinTable( $query, $name = null, $letter = null ) {
		if( $name != null ) {
			$query
				->leftJoin( 'a.'.$name, $letter )
			;
		}
	}
	
}
