<?php

/**
 * BaseTellUs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $last_name
 * @property string $email
 * @property string $mobile
 * @property text $comment
 * 
 * @method string getName()      Returns the current record's "name" value
 * @method string getLastName()  Returns the current record's "last_name" value
 * @method string getEmail()     Returns the current record's "email" value
 * @method string getMobile()    Returns the current record's "mobile" value
 * @method text   getComment()   Returns the current record's "comment" value
 * @method TellUs setName()      Sets the current record's "name" value
 * @method TellUs setLastName()  Sets the current record's "last_name" value
 * @method TellUs setEmail()     Sets the current record's "email" value
 * @method TellUs setMobile()    Sets the current record's "mobile" value
 * @method TellUs setComment()   Sets the current record's "comment" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTellUs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tell_us');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('mobile', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('comment', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}