<?php

/**
 * BaseAssociationSurveyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $association_survey_id
 * @property integer $category_id
 * @property AssociationSurvey $AssociationSurvey
 * @property Category $Category
 * 
 * @method integer                   getAssociationSurveyId()   Returns the current record's "association_survey_id" value
 * @method integer                   getCategoryId()            Returns the current record's "category_id" value
 * @method AssociationSurvey         getAssociationSurvey()     Returns the current record's "AssociationSurvey" value
 * @method Category                  getCategory()              Returns the current record's "Category" value
 * @method AssociationSurveyCategory setAssociationSurveyId()   Sets the current record's "association_survey_id" value
 * @method AssociationSurveyCategory setCategoryId()            Sets the current record's "category_id" value
 * @method AssociationSurveyCategory setAssociationSurvey()     Sets the current record's "AssociationSurvey" value
 * @method AssociationSurveyCategory setCategory()              Sets the current record's "Category" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssociationSurveyCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('association_survey_category');
        $this->hasColumn('association_survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AssociationSurvey', array(
             'local' => 'association_survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}