<?php

/**
 * BaseVolunteerSurveyActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $volunteer_survey_id
 * @property integer $activity_id
 * @property VolunteerSurvey $VolunteerSurvey
 * @property Activity $Activity
 * 
 * @method integer                 getVolunteerSurveyId()   Returns the current record's "volunteer_survey_id" value
 * @method integer                 getActivityId()          Returns the current record's "activity_id" value
 * @method VolunteerSurvey         getVolunteerSurvey()     Returns the current record's "VolunteerSurvey" value
 * @method Activity                getActivity()            Returns the current record's "Activity" value
 * @method VolunteerSurveyActivity setVolunteerSurveyId()   Sets the current record's "volunteer_survey_id" value
 * @method VolunteerSurveyActivity setActivityId()          Sets the current record's "activity_id" value
 * @method VolunteerSurveyActivity setVolunteerSurvey()     Sets the current record's "VolunteerSurvey" value
 * @method VolunteerSurveyActivity setActivity()            Sets the current record's "Activity" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVolunteerSurveyActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('volunteer_survey_activity');
        $this->hasColumn('volunteer_survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('activity_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VolunteerSurvey', array(
             'local' => 'volunteer_survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Activity', array(
             'local' => 'activity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}