<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $location
 * @property integer $order_number
 * @property integer $association_id
 * @property Association $Association
 * 
 * @method string      getLocation()       Returns the current record's "location" value
 * @method integer     getOrderNumber()    Returns the current record's "order_number" value
 * @method integer     getAssociationId()  Returns the current record's "association_id" value
 * @method Association getAssociation()    Returns the current record's "Association" value
 * @method Photo       setLocation()       Sets the current record's "location" value
 * @method Photo       setOrderNumber()    Sets the current record's "order_number" value
 * @method Photo       setAssociationId()  Sets the current record's "association_id" value
 * @method Photo       setAssociation()    Sets the current record's "Association" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('order_number', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('association_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}