<?php

/**
 * BaseVolunteerSurvey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property integer $age
 * @property string $sex
 * @property string $status
 * @property string $status_other
 * @property integer $kids
 * @property string $ethnic
 * @property string $ethnic_other
 * @property string $schooling
 * @property string $schooling_discipline
 * @property string $occupation
 * @property string $nationality
 * @property string $nationality_other
 * @property string $religion
 * @property string $religion_other
 * @property string $voluteering_time
 * @property string $ip_address
 * @property boolean $is_active
 * @property Doctrine_Collection $VolunteerSurvey
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getEmail()                Returns the current record's "email" value
 * @method integer             getAge()                  Returns the current record's "age" value
 * @method string              getSex()                  Returns the current record's "sex" value
 * @method string              getStatus()               Returns the current record's "status" value
 * @method string              getStatusOther()          Returns the current record's "status_other" value
 * @method integer             getKids()                 Returns the current record's "kids" value
 * @method string              getEthnic()               Returns the current record's "ethnic" value
 * @method string              getEthnicOther()          Returns the current record's "ethnic_other" value
 * @method string              getSchooling()            Returns the current record's "schooling" value
 * @method string              getSchoolingDiscipline()  Returns the current record's "schooling_discipline" value
 * @method string              getOccupation()           Returns the current record's "occupation" value
 * @method string              getNationality()          Returns the current record's "nationality" value
 * @method string              getNationalityOther()     Returns the current record's "nationality_other" value
 * @method string              getReligion()             Returns the current record's "religion" value
 * @method string              getReligionOther()        Returns the current record's "religion_other" value
 * @method string              getVoluteeringTime()      Returns the current record's "voluteering_time" value
 * @method string              getIpAddress()            Returns the current record's "ip_address" value
 * @method boolean             getIsActive()             Returns the current record's "is_active" value
 * @method Doctrine_Collection getVolunteerSurvey()      Returns the current record's "VolunteerSurvey" collection
 * @method VolunteerSurvey     setName()                 Sets the current record's "name" value
 * @method VolunteerSurvey     setEmail()                Sets the current record's "email" value
 * @method VolunteerSurvey     setAge()                  Sets the current record's "age" value
 * @method VolunteerSurvey     setSex()                  Sets the current record's "sex" value
 * @method VolunteerSurvey     setStatus()               Sets the current record's "status" value
 * @method VolunteerSurvey     setStatusOther()          Sets the current record's "status_other" value
 * @method VolunteerSurvey     setKids()                 Sets the current record's "kids" value
 * @method VolunteerSurvey     setEthnic()               Sets the current record's "ethnic" value
 * @method VolunteerSurvey     setEthnicOther()          Sets the current record's "ethnic_other" value
 * @method VolunteerSurvey     setSchooling()            Sets the current record's "schooling" value
 * @method VolunteerSurvey     setSchoolingDiscipline()  Sets the current record's "schooling_discipline" value
 * @method VolunteerSurvey     setOccupation()           Sets the current record's "occupation" value
 * @method VolunteerSurvey     setNationality()          Sets the current record's "nationality" value
 * @method VolunteerSurvey     setNationalityOther()     Sets the current record's "nationality_other" value
 * @method VolunteerSurvey     setReligion()             Sets the current record's "religion" value
 * @method VolunteerSurvey     setReligionOther()        Sets the current record's "religion_other" value
 * @method VolunteerSurvey     setVoluteeringTime()      Sets the current record's "voluteering_time" value
 * @method VolunteerSurvey     setIpAddress()            Sets the current record's "ip_address" value
 * @method VolunteerSurvey     setIsActive()             Sets the current record's "is_active" value
 * @method VolunteerSurvey     setVolunteerSurvey()      Sets the current record's "VolunteerSurvey" collection
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVolunteerSurvey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('volunteer_survey');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('age', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sex', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status_other', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('kids', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ethnic', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ethnic_other', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('schooling', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('schooling_discipline', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('occupation', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nationality', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('nationality_other', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('religion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('religion_other', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('voluteering_time', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ip_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ActivitySurvey as VolunteerSurvey', array(
             'local' => 'id',
             'foreign' => 'volunteer_survey_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}