<?php

/**
 * BaseInterestingLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property integer $association_id
 * @property Association $Association
 * 
 * @method string          getUrl()            Returns the current record's "url" value
 * @method integer         getAssociationId()  Returns the current record's "association_id" value
 * @method Association     getAssociation()    Returns the current record's "Association" value
 * @method InterestingLink setUrl()            Sets the current record's "url" value
 * @method InterestingLink setAssociationId()  Sets the current record's "association_id" value
 * @method InterestingLink setAssociation()    Sets the current record's "Association" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInterestingLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('interesting_link');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('association_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}