<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property text $description
 * @property string $picture
 * @property boolean $is_active
 * 
 * @method string  getTitle()       Returns the current record's "title" value
 * @method text    getDescription() Returns the current record's "description" value
 * @method string  getPicture()     Returns the current record's "picture" value
 * @method boolean getIsActive()    Returns the current record's "is_active" value
 * @method News    setTitle()       Sets the current record's "title" value
 * @method News    setDescription() Sets the current record's "description" value
 * @method News    setPicture()     Sets the current record's "picture" value
 * @method News    setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));

        $this->option('orderBy', 'created_at ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}