<?php

/**
 * BaseVolunteerSurveyAssociationSurvey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $volunteer_survey_id
 * @property integer $association_survey_id
 * @property VolunteerSurvey $VolunteerSurvey
 * @property AssociationSurvey $AssociationSurvey
 * 
 * @method integer                          getVolunteerSurveyId()     Returns the current record's "volunteer_survey_id" value
 * @method integer                          getAssociationSurveyId()   Returns the current record's "association_survey_id" value
 * @method VolunteerSurvey                  getVolunteerSurvey()       Returns the current record's "VolunteerSurvey" value
 * @method AssociationSurvey                getAssociationSurvey()     Returns the current record's "AssociationSurvey" value
 * @method VolunteerSurveyAssociationSurvey setVolunteerSurveyId()     Sets the current record's "volunteer_survey_id" value
 * @method VolunteerSurveyAssociationSurvey setAssociationSurveyId()   Sets the current record's "association_survey_id" value
 * @method VolunteerSurveyAssociationSurvey setVolunteerSurvey()       Sets the current record's "VolunteerSurvey" value
 * @method VolunteerSurveyAssociationSurvey setAssociationSurvey()     Sets the current record's "AssociationSurvey" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVolunteerSurveyAssociationSurvey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('volunteer_survey_association_survey');
        $this->hasColumn('volunteer_survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('association_survey_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VolunteerSurvey', array(
             'local' => 'volunteer_survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('AssociationSurvey', array(
             'local' => 'association_survey_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}