<?php

/**
 * BaseAssociationDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $association_id
 * @property integer $department_id
 * @property Association $Association
 * @property Department $Department
 * 
 * @method integer               getAssociationId()  Returns the current record's "association_id" value
 * @method integer               getDepartmentId()   Returns the current record's "department_id" value
 * @method Association           getAssociation()    Returns the current record's "Association" value
 * @method Department            getDepartment()     Returns the current record's "Department" value
 * @method AssociationDepartment setAssociationId()  Sets the current record's "association_id" value
 * @method AssociationDepartment setDepartmentId()   Sets the current record's "department_id" value
 * @method AssociationDepartment setAssociation()    Sets the current record's "Association" value
 * @method AssociationDepartment setDepartment()     Sets the current record's "Department" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssociationDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('association_department');
        $this->hasColumn('association_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('department_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Department', array(
             'local' => 'department_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}