<?php

/**
 * BaseState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Associations
 * @property Doctrine_Collection $State
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getAssociations() Returns the current record's "Associations" collection
 * @method Doctrine_Collection getState()        Returns the current record's "State" collection
 * @method State               setName()         Sets the current record's "name" value
 * @method State               setAssociations() Sets the current record's "Associations" collection
 * @method State               setState()        Sets the current record's "State" collection
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseState extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('state');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}
