<?php

/**
 * BaseActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property date $date
 * @property text $description
 * @property text $place
 * @property string $picture
 * @property integer $association_id
 * @property boolean $is_active
 * @property Association $Association
 * 
 * @method string      getTitle()          Returns the current record's "title" value
 * @method date        getDate()           Returns the current record's "date" value
 * @method text        getDescription()    Returns the current record's "description" value
 * @method text        getPlace()          Returns the current record's "place" value
 * @method string      getPicture()        Returns the current record's "picture" value
 * @method integer     getAssociationId()  Returns the current record's "association_id" value
 * @method boolean     getIsActive()       Returns the current record's "is_active" value
 * @method Association getAssociation()    Returns the current record's "Association" value
 * @method Activity    setTitle()          Sets the current record's "title" value
 * @method Activity    setDate()           Sets the current record's "date" value
 * @method Activity    setDescription()    Sets the current record's "description" value
 * @method Activity    setPlace()          Sets the current record's "place" value
 * @method Activity    setPicture()        Sets the current record's "picture" value
 * @method Activity    setAssociationId()  Sets the current record's "association_id" value
 * @method Activity    setIsActive()       Sets the current record's "is_active" value
 * @method Activity    setAssociation()    Sets the current record's "Association" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('place', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('association_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));

        $this->option('orderBy', 'date ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}