<?php

/**
 * BaseAssociationCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $association_id
 * @property integer $category_id
 * @property Association $Association
 * @property Category $Category
 * 
 * @method integer             getAssociationId()  Returns the current record's "association_id" value
 * @method integer             getCategoryId()     Returns the current record's "category_id" value
 * @method Association         getAssociation()    Returns the current record's "Association" value
 * @method Category            getCategory()       Returns the current record's "Category" value
 * @method AssociationCategory setAssociationId()  Sets the current record's "association_id" value
 * @method AssociationCategory setCategoryId()     Sets the current record's "category_id" value
 * @method AssociationCategory setAssociation()    Sets the current record's "Association" value
 * @method AssociationCategory setCategory()       Sets the current record's "Category" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssociationCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('association_category');
        $this->hasColumn('association_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Association', array(
             'local' => 'association_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}