<?php

/**
 * BaseActivitySurvey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $volunteer_survey_id
 * @property integer $association_survey_id
 * @property integer $field1
 * @property integer $field2
 * @property integer $field3
 * @property integer $field4
 * @property integer $field5
 * @property integer $field6
 * @property integer $field7
 * @property integer $field8
 * @property integer $field9
 * @property integer $field10
 * @property integer $field11
 * @property integer $field12
 * @property integer $field13
 * @property integer $field14
 * @property integer $field15
 * @property integer $field16
 * @property text $field17
 * @property AssociationSurvey $AssociationSurvey
 * @property VolunteerSurvey $VolunteerSurvey
 * 
 * @method integer           getVolunteerSurveyId()     Returns the current record's "volunteer_survey_id" value
 * @method integer           getAssociationSurveyId()   Returns the current record's "association_survey_id" value
 * @method integer           getField1()                Returns the current record's "field1" value
 * @method integer           getField2()                Returns the current record's "field2" value
 * @method integer           getField3()                Returns the current record's "field3" value
 * @method integer           getField4()                Returns the current record's "field4" value
 * @method integer           getField5()                Returns the current record's "field5" value
 * @method integer           getField6()                Returns the current record's "field6" value
 * @method integer           getField7()                Returns the current record's "field7" value
 * @method integer           getField8()                Returns the current record's "field8" value
 * @method integer           getField9()                Returns the current record's "field9" value
 * @method integer           getField10()               Returns the current record's "field10" value
 * @method integer           getField11()               Returns the current record's "field11" value
 * @method integer           getField12()               Returns the current record's "field12" value
 * @method integer           getField13()               Returns the current record's "field13" value
 * @method integer           getField14()               Returns the current record's "field14" value
 * @method integer           getField15()               Returns the current record's "field15" value
 * @method integer           getField16()               Returns the current record's "field16" value
 * @method text              getField17()               Returns the current record's "field17" value
 * @method AssociationSurvey getAssociationSurvey()     Returns the current record's "AssociationSurvey" value
 * @method VolunteerSurvey   getVolunteerSurvey()       Returns the current record's "VolunteerSurvey" value
 * @method ActivitySurvey    setVolunteerSurveyId()     Sets the current record's "volunteer_survey_id" value
 * @method ActivitySurvey    setAssociationSurveyId()   Sets the current record's "association_survey_id" value
 * @method ActivitySurvey    setField1()                Sets the current record's "field1" value
 * @method ActivitySurvey    setField2()                Sets the current record's "field2" value
 * @method ActivitySurvey    setField3()                Sets the current record's "field3" value
 * @method ActivitySurvey    setField4()                Sets the current record's "field4" value
 * @method ActivitySurvey    setField5()                Sets the current record's "field5" value
 * @method ActivitySurvey    setField6()                Sets the current record's "field6" value
 * @method ActivitySurvey    setField7()                Sets the current record's "field7" value
 * @method ActivitySurvey    setField8()                Sets the current record's "field8" value
 * @method ActivitySurvey    setField9()                Sets the current record's "field9" value
 * @method ActivitySurvey    setField10()               Sets the current record's "field10" value
 * @method ActivitySurvey    setField11()               Sets the current record's "field11" value
 * @method ActivitySurvey    setField12()               Sets the current record's "field12" value
 * @method ActivitySurvey    setField13()               Sets the current record's "field13" value
 * @method ActivitySurvey    setField14()               Sets the current record's "field14" value
 * @method ActivitySurvey    setField15()               Sets the current record's "field15" value
 * @method ActivitySurvey    setField16()               Sets the current record's "field16" value
 * @method ActivitySurvey    setField17()               Sets the current record's "field17" value
 * @method ActivitySurvey    setAssociationSurvey()     Sets the current record's "AssociationSurvey" value
 * @method ActivitySurvey    setVolunteerSurvey()       Sets the current record's "VolunteerSurvey" value
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActivitySurvey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('activity_survey');
        $this->hasColumn('volunteer_survey_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('association_survey_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('field1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field6', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field7', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field8', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field9', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field10', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field11', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field12', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field13', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field14', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field15', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field16', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('field17', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));

        $this->option('orderBy', 'created_at ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AssociationSurvey', array(
             'local' => 'association_survey_id',
             'foreign' => 'id'));

        $this->hasOne('VolunteerSurvey', array(
             'local' => 'volunteer_survey_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}