<?php

/**
 * BaseLibrary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property text $description
 * @property string $picture
 * @property string $media
 * @property string $type
 * @property boolean $is_active
 * @property integer $rating
 * @property Doctrine_Collection $Library
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method text                getDescription() Returns the current record's "description" value
 * @method string              getPicture()     Returns the current record's "picture" value
 * @method string              getMedia()       Returns the current record's "media" value
 * @method string              getType()        Returns the current record's "type" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method integer             getRating()      Returns the current record's "rating" value
 * @method Doctrine_Collection getLibrary()     Returns the current record's "Library" collection
 * @method Library             setTitle()       Sets the current record's "title" value
 * @method Library             setDescription() Sets the current record's "description" value
 * @method Library             setPicture()     Sets the current record's "picture" value
 * @method Library             setMedia()       Sets the current record's "media" value
 * @method Library             setType()        Sets the current record's "type" value
 * @method Library             setIsActive()    Sets the current record's "is_active" value
 * @method Library             setRating()      Sets the current record's "rating" value
 * @method Library             setLibrary()     Sets the current record's "Library" collection
 * 
 * @package    quehagoporti
 * @subpackage model
 * @author     Jose Alfredo Alvarez Aldana
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibrary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('library');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('media', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('LibraryRating as Library', array(
             'local' => 'id',
             'foreign' => 'library_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}