<?php

namespace World\VolunteerBundle\Entity\Repositories;

use World\ToolBundle\Entity\Repositories\BaseRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends BaseRepository
{

    public function findAllQuery( $enabled = null ) {

        $today = new \DateTime();

        $queryBuilder = $this->findAllQueryBuilder( $enabled )->orderBy('a.date', 'ASC');

        $queryBuilder
            ->andWhere('a.date >= :today')
            ->setParameter('today', $today->format('Y-m-d'))
        ;

        return $queryBuilder->getQuery();
    }

    public function findAllCustom( $enabled = null ) {
        return $this->findAllQuery( $enabled )->execute();
    }

}
