<?php

namespace World\VolunteerBundle\Entity\Repositories;

use World\ToolBundle\Entity\Repositories\BaseRepository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends BaseRepository
{
}
