<?php

namespace World\VolunteerBundle\Entity\Repositories;

use World\ToolBundle\Entity\Repositories\BaseRepository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends BaseRepository
{

    public function findAllQuery( $enabled = null ) {
        $queryBuilder = $this->findAllQueryBuilder( $enabled )->orderBy('a.randomValue', 'ASC');

        return $queryBuilder->getQuery();
    }

    public function findAllCustom( $enabled = null ) {
        return $this->findAllQuery( $enabled )->execute();
    }

}
