photo_photo:
  class: sfDoctrineRouteCollection
  options:
    model:                Photo
    module:               photo
    prefix_path:          /photo
    column:               id
    with_wildcard_routes: true

photo:
  class: sfDoctrineRouteCollection
  options:
    model:                Photo
    module:               video
    prefix_path:          /video
    column:               id
    with_wildcard_routes: true

video:
  class: sfDoctrineRouteCollection
  options:
    model:                Video
    module:               video
    prefix_path:          /video
    column:               id
    with_wildcard_routes: true

testimonial:
  class: sfDoctrineRouteCollection
  options:
    model:                Testimonial
    module:               testimonial
    prefix_path:          /testimonial
    column:               id
    with_wildcard_routes: true

volunteer_survey:
  class: sfDoctrineRouteCollection
  options:
    model:                VolunteerSurvey
    module:               volunteer_survey
    prefix_path:          /volunteer_survey
    column:               id
    with_wildcard_routes: true

association_survey:
  class: sfDoctrineRouteCollection
  options:
    model:                AssociationSurvey
    module:               association_survey
    prefix_path:          /association_survey
    column:               id
    with_wildcard_routes: true

category:
  class: sfDoctrineRouteCollection
  options:
    model:                Category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

library:
  class: sfDoctrineRouteCollection
  options:
    model:                Library
    module:               library
    prefix_path:          /library
    column:               id
    with_wildcard_routes: true

news:
  class: sfDoctrineRouteCollection
  options:
    model:                News
    module:               news
    prefix_path:          /news
    column:               id
    with_wildcard_routes: true

tagging:
  class: sfDoctrineRouteCollection
  options:
    model:                Tagging
    module:               tagging
    prefix_path:          /tagging
    column:               id
    with_wildcard_routes: true

tag:
  class: sfDoctrineRouteCollection
  options:
    model:                Tag
    module:               tag
    prefix_path:          /tag
    column:               id
    with_wildcard_routes: true

activity:
  class: sfDoctrineRouteCollection
  options:
    model:                Activity
    module:               activity
    prefix_path:          /activity
    column:               id
    with_wildcard_routes: true

association:
  class: sfDoctrineRouteCollection
  options:
    model:                Association
    module:               association
    prefix_path:          /association
    column:               id
    with_wildcard_routes: true

town:
  class: sfDoctrineRouteCollection
  options:
    model:                Town
    module:               town
    prefix_path:          /town
    column:               id
    with_wildcard_routes: true

department:
  class: sfDoctrineRouteCollection
  options:
    model:                Department
    module:               department
    prefix_path:          /department
    column:               id
    with_wildcard_routes: true

country:
  class: sfDoctrineRouteCollection
  options:
    model:                Country
    module:               country
    prefix_path:          /country
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: association, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
