# Acme/DemoBundle/Resources/config/admin.yml
services:
    sonata.admin.user:
        class: World\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - World\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]