world_admin:
    resource: "@WorldAdminBundle/Resources/config/routing.yml"
    prefix:   /

world_dashboard:
    resource: "@WorldDashboardBundle/Resources/config/routing.yml"
    prefix:   /

world_user:
    resource: "@WorldUserBundle/Resources/config/routing.yml"
    prefix:   /

world_tool:
    resource: "@WorldToolBundle/Resources/config/routing.yml"
    prefix:   /

world_volunteer:
    resource: "@WorldVolunteerBundle/Resources/config/routing.yml"
    prefix:   /


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin