# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
                always_use_default_target_path: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }


        # Just in case
        - { path: ^/slide/, role: ROLE_ADMIN }
        - { path: ^/news/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_ADMIN }
        - { path: ^/activity/, role: ROLE_ADMIN }
        - { path: ^/testimonial/, role: ROLE_ADMIN }
        - { path: ^/photo/, role: ROLE_ADMIN }
        - { path: ^/video/, role: ROLE_ADMIN }

        - { path: create$, role: ROLE_ADMIN }
        - { path: new$, role: ROLE_ADMIN }
        - { path: update$, role: ROLE_ADMIN }
        - { path: edit$, role: ROLE_ADMIN }
        - { path: delete$, role: ROLE_ADMIN }
        # END Just in case

        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }